import type { Metadata } from "next";
import { Inter } from "next/font/google";
import styles from "./styles.module.css";
import "../styles/global.css";
import Header from "../components/Header/index";
import Footer from "../components/Footer/index";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Blog-App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={inter.className}>
      <body className={styles.container}>
        <Header />
        <main>
          <p> {children}</p>
        </main>
        <Footer />
      </body>
    </html>
  );
}
